name: OKDOSE dApp - CI

on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  build-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.OKDOSE_DAPP_CONTRACTS_DEPLOY_KEY }}
          submodules: 'recursive'

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: "Install the project"
        run: yarn

      - name: "Build project"
        run: yarn build

      - name: "Run the tests"
        run: yarn test

      - name: "Run linter"
        run: yarn lint
